name: Update Progress Tracker

on:
  push:
    paths:
      - '**/*.java'
      - '**/done.txt'
      - '**/in_progress.txt'
  schedule:
    - cron: '0 0 * * *'  # every day at midnight UTC
  workflow_dispatch:

jobs:
  update-tracker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run badge generator
        run: python .github/scripts/generate_progress.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add PROGRESS.md
          git commit -m "🔄 Auto-update progress tracker"
          git push
